### ISSUE TITLE
Нужна модификация под требования

### ISSUE THREAD

**Issue by pinetree** [orbita-center/react-dadata-box#11]
### Требования к модификации react-dadata-box
* Документация Dadata: https://confluence.hflabs.ru/pages/viewpage.action?pageId=204669108
* Tips Dadata: https://dadata.userecho.com/knowledge-bases/4/articles/2090-kak-sdelat-vsyo-chto-ugodno-v-podskazkah

### Пример формы 
![image](https://user-images.githubusercontent.com/568896/63247878-c17e9400-c26e-11e9-91a4-bff327a6f943.png)

### 1. Значения: все населённые пункты мира

Добавить props 
```
constraints = {
    locations: [{"country":"*"}],
    from_bound: {value: "city"}
    restrict_value: false
    to_bound: {value: "settlement"}
}
```

* `restrict_value: true` - так в результате будет адрес полной строкой
"Смоленская обл, Починковский р-н, деревня Кукуево"

* `restrict_value: false` - остается только последний параметр (нас.пункт)
"деревня Кукуево"

### 2. Значения: все регионы России и страны мира.

Тут по идее надо делать 2 запроса

https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/address
https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/country

Пока не готов сказать, реально ли в одном контроле искать и по регионам РФ и по странам мира.

### 3. Значения: все страны мира.

Есть пропс `type`. Но сейчас он допускает только адрес(address), организация(party) или банк(bank), почта(email), 
фио(fio).
Добавить country.

### 4.  Значения: все районы внутри выбранной страны. 

Имеем выбранную страну: Россия

тогда в constraint добавляем 
```
{
    locations: [{country: "Россия"}],
    from_bound: {value: "region"},
    to_bound: {value: "region"}
}
```

Результаты - все регионы России. ***Для многих стран не работает***.

### 5. Значения: все районы внутри выбранного региона.

Имеем выбранную страну: Россия
выбранную область: Московская обл  

тогда в constraint добавляем 
```
{
    locations: [{country: "Россия", region: "московская"}]
    from_bound: {value: "area"},
    to_bound: {value: "area"},
}
```
\* в region тут именно "московская", одно слово, без "обл"

\** лучше хранить кроме текстового value, идентификатор kladr_id или fias_id

### 6. Значения: все населенные пункты внутри выбранного района.

Имеем выбранную страну: Россия
выбранную область: Московская обл  
выбранный район: Пушкинский р-н

тогда в constraint добавляем 
```
{
    locations: [{country: "Россия", region: "московская", area: "пушкинский"}]
    from_bound: {value: "city"},
    to_bound: {value: "settlement"}
}
```

Пример результата: тер. СНТ Пушкино

### 7. Адрес	Комбобокс без стрелки. Подключена «Дадата»

Тут просто ищем адрес. Это уже есть.

### 8. Поле может принимать пользовательский ввод, то есть работать как простой Input.
Случаи: когда Район внутри выбранной страны/региона не найден, но при этом поле является обязательным к заполнению.

![image](https://user-images.githubusercontent.com/568896/63248220-8761c200-c26f-11e9-8fa4-b23047dd888e.png)

Тут Дадата не возвращает ничего по поиску района в Дании.

Решение: добавить пропс allowCustomValue

### 9. Возможность удалять начатый ввод onBlur.
Пример: начали вводить "Рос" - появились варианты, но мы передумали. По клику outside/onBlur мы хотим чтобы в поле ничего не осталось, чтобы оно очистилось.

Решение: добавить пропс clearOnBlur, по-умолчанию false.

### 10. Добавить свой value accessor.
Пример: мы можем хотеть получить в ответе от компонента не просто `value`, например только название самого города, просто "Москва".
Или взять из ответа (свойства `data`) название населенного пункта ИЛИ название города, если найден город (это city_with_type или settlement_with_type). 

Решение: добавить кастомный  value accessor как пропс, dataExtract.

В таком случае, задав 
```dataExtract={({ city_with_type, settlement_with_type }) =>city_with_type || settlement_with_type}```
мы получим в ответе в поле `value` уже нужное значение.

### 11. Добавить пропс fetchOnMount.
Сейчас по-умолчанию на componentDidMount мы выполняем `fetchSuggestions`.
Это нужно не всегда.
Иногда совсем не нужно - например когда поля уже предзаполнены данными, в форме их десятки штук - получаем десятки запросов на фетч данных от Dadata. Хотя нам достаточно просто текстовых значений в форме, и фетчить все варианты на mount не требуется.

Решение: добавить пропс fetchOnMount. По-умолчанию `false`.

### 12. Добавить Label.

Иногда требуется наличие label у input-поля. У нас в проекте Ant и на label завязан показ ошибок (подсветка поля красным и вывод текста ошибки в label:after).

![image](https://user-images.githubusercontent.com/568896/63249227-b6793300-c271-11e9-8822-0aa4c7827619.png)

Решение: добавить пропс label.

### 13. На ввод * или \ приложение падает из-за ошибки в парсинге RegExp в компоненте Highlighter.

Решение: в getHighlightWords пропускать query через функцию 
```
const escapeForRegexp = string => string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
```

------

### Общее.
Добавить пропс `constraints: Object` с форматом данных совпадающим с документаций dadata по "Ограничение сектора поиска адреса (API)" https://confluence.hflabs.ru/pages/viewpage.action?pageId=204669108

**Comment by RUVATA** [comment]
> 1. Значения: все населённые пункты мира ...

> 4. Значения: все районы внутри выбранной страны ...

> 5. Значения: все районы внутри выбранного региона ...

> 6. Значения: все населенные пункты внутри выбранного района ...

предлагаю подумать насчет _prop_ типо **extraQuery** значение которого (произвольный объект) будет ассайниться с **query** внутреннего состояния
```javascript
const payloadObject = {...this.props.extraQuery, query: this.state.query}
```
не хочется захламлять компонент кастомными реализациями параметров (коих 100500)
конечный разработчик волен будет как угодно их формировать - **но снаружи.**
вот эти  уже внедренные **частные случаи** тоже бы тогда выпилить...
```javascript
    if (city && type === 'address') {
      payload.from_bound = { value: 'city' };
      payload.to_bound = { value: 'settlement' };
      payload.value = 'settlement';
    }
```
что думаешь ?

**Comment by RUVATA** [comment]
> 3. Значения: все страны мира.
> ...
> Добавить country.

`возражений/комментариев - нет`

**Comment by pinetree** [comment]
> > 1. Значения: все населённые пункты мира ...
> 
> > 1. Значения: все районы внутри выбранной страны ...
> 
> > 1. Значения: все районы внутри выбранного региона ...
> 
> > 1. Значения: все населенные пункты внутри выбранного района ...
> 
> предлагаю подумать насчет _prop_ типо **extraQuery** значение которого (произвольный объект) будет ассайниться с **query** внутреннего состояния
> 
> ```js
> const payloadObject = {...this.props.extraQuery, query: this.state.query}
> ```
> 
> не хочется захламлять компонент кастомными реализациями параметров (коих 100500)
> конечный разработчик волен будет как угодно их формировать - **но снаружи.**
> вот эти уже внедренные **частные случаи** тоже бы тогда выпилить...
> 
> ```js
>     if (city && type === 'address') {
>       payload.from_bound = { value: 'city' };
>       payload.to_bound = { value: 'settlement' };
>       payload.value = 'settlement';
>     }
> ```
> 
> что думаешь ?

ну да, я так примерно и сделал, назвав этот объект `constraints`.
Вот тут код, который сейчас я использую у себя https://github.com/pinetree/react-dadata-box/blob/feature/more-options/src/index.js

Действительно, все реализации всех случаев я вынес в клиентский код, там у меня достаточно интересно получилось) До того, что я подумывал даже перенести потом это в библиотеку. Но скорее всего ты прав, наличие вот таких props как `city={true}` только на первый взгляд облегчают использование. Точнее до первого более-менее сложного случая, когда потребуется лезть в доку Dadata и думать как это реализовать в рамках компонента.

**Comment by RUVATA** [comment]
> 8. Поле может принимать пользовательский ввод, то есть работать как простой Input.

- вот тут надо подумать, смысл в том что предназначение компонента предоставлять на выход объект дадаты, в данном случае будет "размытие сигнатуры" если предоставлять кастомное поведение на тот же хендлер (при чем следует тут заметить что мы забиндили **onChange** хотя наверное следовало бы **onSelect** и тогда **onChange** можно было бы пробрасывать в нативный инпут и там уже разработчик опять таки "снаружи" мог бы обрабатывать это как хочет, разве что можно было бы из коробки дать возможность тролинг/дебаунсинг настраивать для него) но тут у нас дилема - без вкрячивания обратной совместимости хендлер менять не желательно.
- вопрос второй, если все таки не вводить отдельный хендлер, то возможно предусмотреть опциональные выбрасывание в **onSelect** на **onBlure** инпута типо синтетического объекта от дадаты где не засетаплено ничего кроме **value** (но ИМХО - это "такое")

моя идея заключается вот в таком "ноу хау" мне кажется будет очень даже интересным решение, если мы введем пропсу (render prop) в которую можно будет скинуть альтернативный инпут, который автоматически будет подставляться вместо родного (когда от DaData по текущему набору **query** + **constraints** ничего от дадаты не пришло), при рендере такого компонента ему на вход будет подаваться **query** и **onChange** (который подразумевается использовать в своей реализации хендлера - если надо дублируя туда изменения, чтобы при изменении **query** компонент мог проверять не появились ли варианты, и если да - то свитчить свою реализацию назад)
надеюсь получилось объяснить идею.
@pinetree что думаешь ?

**Comment by RUVATA** [comment]
> 9. Возможность удалять начатый ввод onBlur.
Пример: начали вводить "Рос" - появились варианты, но мы передумали. По клику outside/onBlur мы хотим чтобы в поле ничего не осталось, чтобы оно очистилось.
Решение: добавить пропс clearOnBlur, по-умолчанию false.

Предлагаю возможно более "гибкое решение" - просто реализовать для разработчика хендлер **onBlur** но передавать ему на вход _помимо стандартного события от инпута - функцию (уcловно н/п **setQuery** вызов которой со значением - модифицирует внутреннее состояние)_ а там разработчик что хочет то и сделает - передаст пустую строку - дропнет, а может и накрутить какую ни будь подстановку дефолта, или как вариант - подстановку предыдущего (успешного значения) если был не ввод "с нуля" а например чендж ранее выбранного, ну и вообщем любую логику, всякое бывает надо на **onBlur** повесить.
Так не сильно расширяя интерфейс - хорошо развиваем форматы применения и решаем изначальную задачу в т.ч.
@pinetree что думаешь ?

**Comment by RUVATA** [comment]
> 10. Добавить свой value accessor
...
dataExtract={({ city_with_type, settlement_with_type }) =>city_with_type || settlement_with_type}
мы получим в ответе в поле value уже нужное значение.

мне кажется избыточно - есть **onChange** сделай хендлер из композиции своего **accessor** и логики итогового разбора значения. (ведь внутри будет просто то же самое мы сделаем композицию `props.onChange(props.dataExtract(suggestion)))` при этом **onChange** еще и потеряет строгую сигнатуру (Хотя описать типы можно будет чтобы при установленном **dataExtract** типизация входа на **onChange** выводилась из возвращаемого ей типа)

Но я если честно не вижу вообще в этом смысла - т.к. экстрактор закомпозировать можно будет как угодно в штатный **onChange**
@pinetree нужен ли такой проп в действительности ?

**Comment by RUVATA** [comment]
> 11. Добавить пропс fetchOnMount.
> Сейчас по-умолчанию на componentDidMount мы выполняем fetchSuggestions.
> Это нужно не всегда.
> ...
> Решение: добавить пропс fetchOnMount. По-умолчанию false.

идея хорошая, годная, нужная, только стоит обсудить тезис относительно значения по умолчанию - сейчас поведение как бы "true" по дефолту, как бы опять таки ломаем обратную совместимость меняя поведение на "false"
@pinetree так что может быть все таки дефолтом - **true** ?

**Comment by RUVATA** [comment]
> 12. Добавить Label.
> Иногда требуется наличие label у input-поля.

Вот тут я хотел бы "поборотся" :) Лейбл это функциональная часть слота формы в которой используется компонент, форма и ее концепт может требовать лейбл слева, справа, сверху, снизу, с шапито и акробатами, вкрячивать этот функционал (в каком то конкретном виде казуально, лучше оставить лейблинг форме в которой компонент будут использоваться как контрол) в реализации самого поля - не вижу особого смысла, еще и потому что это отдельно взятый компонент (это не чать однообразного UI.Kit) и он вряд ли будет использоваться одинв форме а лейблы у всех элементов формы 99% требуют однотипности

Так же, часть решений которые предоставляют движки форм подразумеваю помещение контролов в абстрактные **Filed** врапперы - которые зачастую реализую как раз "слот" с лейблом (н/п Ant.Design) или например React.Bootstrap подразумевает лейбл как отдельный компонент **Form.Label** вообщем тут нет универсального подхода - а частный случай тут тоже особо не нужен т.к. компонент как раз таки пытается быть универсальным.
@pinetree такова моя аргументация, надеюсь не очень сумбурно.

**Comment by RUVATA** [comment]
> 13. На ввод * или \ приложение падает из-за ошибки в парсинге RegExp в компоненте Highlighter.
> Решение: в getHighlightWords пропускать query через функцию...

в документации нашел вот такой проп
![image](https://user-images.githubusercontent.com/2040022/63303780-87060d00-c2e9-11e9-84eb-9f0371fe8d9a.png)
судя из описания - это вроде "оно"
@pinetree - не пробовал ? не решает ли это проблему, если да - то лучше использовать инстанс решение - чем внешнее собственноручное экранирование.

**Comment by RUVATA** [comment]
что касается **constraints**
![image](https://user-images.githubusercontent.com/2040022/63304045-57a3d000-c2ea-11e9-99ee-cfcaf3c20693.png)
мне кажется само слово (**constraints** - ограничения) не может быть нормальным обобщением для полей одноранговых (т.е. на том же уровне) с **query** и **count**, так как мы мержим как-бы объект с **query** и **count** с пользовательским объектом (как бы его половчее назвать :)) в котором предусматривается еще группа логических свойств (_locations, locations_boost, from_bound/to_bound_) из которых логически "ограничением" является только узел **locations**
@pinetree предлагаю еще подумать над именованием этого свойства.

**Comment by legiorex** [comment]
Здравствуйте, сейчас можно как-то передать locations? Если да, то как? 
Спасибо.

**Comment by pinetree** [comment]
> Здравствуйте, сейчас можно как-то передать locations? Если да, то как?
> Спасибо.

Добрый день,
все что тут обсуждалось реализовано в https://github.com/pinetree/react-dadata-box , в оригинальный репо пока PR не делался (из-за спорных моментов в реализации).

Но в форке locations передать можно, в constraints.

Посмотрите там examples.

**Comment by legiorex** [comment]
Сейчас мне надо заменить код этой библиотеки на вашу? Правильно?

**Comment by pinetree** [comment]
"react-dadata-box": "github:pinetree/react-dadata-box",

можно в `package.json` указать так. 
Но еще раз - это личная версия, на релиз не претендует, хотя и работает.

**Comment by legiorex** [comment]
Спасибо, всё работает. Правда я вручную код добавил - сейчас сделаю как вы посоветовали.
И еще вопрос - как можно реализовать выбор только предложенного адреса? Ну что бы пользователь не мог свой ввести, например какой-то не существующий?

**Comment by pinetree** [comment]
> Спасибо, всё работает. Правда я вручную код добавил - сейчас сделаю как вы посоветовали.
> И еще вопрос - как можно реализовать выбор только предложенного адреса? Ну что бы пользователь не мог свой ввести, например какой-то не существующий?

Я может быть не понял вопрос,
но если `allowCustomValue` === false (а по-умолчанию он false), то input работает только как Select, то есть мы можем только выбрать из предложенных.

Или вам нужно изначально иметь в списке ограниченное число результатов по какому-то запросу? То есть ничего не пишем в input, а просто по focus`у выдаем список?

**Comment by legiorex** [comment]
Да, ничего не пишем в input. Или пишем, но он даст написать адрес которого нет в выдаче. Или ошибку отправит.

**Comment by pinetree** [comment]
Но изначальный запрос вам все равно нужно иметь.
Тогда задаем пропсы 
```
query="Москва, ул. Ленина"
fetchOnMount={true}
```

Поле input будет предзаполнено. По клику выдаст результаты.
Если нужно запретить его менять, то можно поиграть с `onChange` или придумать что-то другое.

**Comment by legiorex** [comment]
Хорошо, я понял. Спасибо большое.

**Comment by RUVATA** [comment]
@inver спасибо за внимание, в ближайшем времени функциональность (возможно с небольшими изменениями будет ассимилирована в основную версию пакета) следите за обновлениями :)
