### ISSUE TITLE
Error on party type

### ISSUE THREAD

**Issue by therealsqvad** [orbita-center/react-dadata-box#14]
Возникает ошибка 
```
TypeError: Cannot read property 'value' of null at SuggestionInfo
```
при вводе **"ип ф"** или **"ип б"**, с остальными буквами ошибка не возникает

Также возникает ошибка 
`SyntaxError: Invalid regular expression: /\/: \ at end of pattern at new RegExp (<anonymous>)`
если начать ввод с **'\\'**

**Comment by pinetree** [comment]
Есть такое.
можно решить так https://github.com/pinetree/react-dadata-box/pull/2/commits/53fa9cb5c4ac0f6e3db1c73d0bce2926f2d6b596

**Comment by RUVATA** [comment]
> "ип ф"
![image](https://user-images.githubusercontent.com/2040022/66112826-3cf49480-e5d4-11e9-8e90-4062c70d5626.png)

> "ип б"
![image](https://user-images.githubusercontent.com/2040022/66112859-4b42b080-e5d4-11e9-95c9-5ed7747e418f.png)

обрабатывается корректно - ошибку не могу воспроизвести
@therealsqvad можете подробнее описать что происходит ?

**Comment by RUVATA** [comment]
@therealsqvad спасибо, проблема обнаружена, ошибка при формировании строки с дополнительной информацией, где безусловно принималось что у всех найденных в **DaData** организаций такая информация (как минимум адрес) имеется
но как  оказалось - нет - "ип ф" и "ип б" как раз дают подобное в своих выборках
![image](https://user-images.githubusercontent.com/2040022/66115043-b7bfae80-e5d8-11e9-8caa-c1b330324c7b.png)

пример, где нет ни _адреса_ ни _ИНН_ 
![image](https://user-images.githubusercontent.com/2040022/66115263-27359e00-e5d9-11e9-8215-b605bfedc747.png)

**Comment by therealsqvad** [comment]
Да, я тоже обнаружил проблему именно с этим ИП, поскольку у него не указан адрес и инн

**Comment by RUVATA** [comment]
@therealsqvad актуальная версия опубликована на NPM в виде пакета, можете обновляться.
