### ISSUE TITLE
Предоставить класс или инлайн стили для компонента suggestions

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [orbita-center/react-dadata-box#33]
Было бы здорово, если бы была возможность предоставить возможность списку dadata, а именно компоненту suggestions возможность добавлять свои инлайн стили или свой класс, для более удобного контролирования стилей, например, сценарий, когда надо список точек dadata отображать сверху, над инпутом, на тех же моб. устройствах, тк на некоторых дейвайсах, клавиатура может уезжать прямо до инпута, в следствии чего не всегда удобно работать со списком.

**Comment by RUVATA** [comment]
- [ ] implement **customStyles** property, typed as
```typescript
{
    'react-dadata__custom-action': string | React.CSSProperties;
    'react-dadata__suggestion': string | React.CSSProperties;
    'react-dadata__suggestion-note': string | React.CSSProperties;
    'react-dadata__suggestions': string | React.CSSProperties;
}
```
where:
- **available keys:** native classNames of embedded nodes of main component
```typescript
  "react-dadata__suggestions" | "react-dadata__suggestion"
| "react-dadata-custom-action" | "react-dadata__suggestion-note"
```
- **values:** is custom styling

**--->** if **object** (`React.CSSProperties` TS type), that interpreted as object to setup it into **style** property of  relevant nodes
    [_for example_] if **customStyles** property is:
```javascript
{
     react-dadata__suggestions: 
        {
          top: '200px',
          position: 'absolute'
        }
}
``` 
**suggestions** block will be renderder as
```html
<div classname="react-dadata__suggestions" style="top: 200px;  position: absolute;"> 
...
```
**--->** if **string**, that interpreted as additional classname to relevant nodes
    [_for example_] if **customStyles** property is:
```javascript
{ react-dadata__suggestions: 'my-extra-class'}
``` 
**suggestions** block will be renderder as
```html
<div className="react-dadata__suggestions my-extra-class"> 
...
```

**Comment by RUVATA** [comment]
@TchernyavskyDaniil 
requested functionality assimilated (#35) by RC branch, after it will be merged to master, new version of NPM-package will be published.

**Comment by RUVATA** [comment]
@TchernyavskyDaniil 
at now v1.3.3 released on NPM, welcome to update.
note that updated the README documentation and added codesandbox playground with examples of usage some functionality. (in particular **customStyles** property)
