### ISSUE TITLE
Добавить возможность ввода произвольного значения

### ISSUE THREAD

**Issue by ekabolotina** [orbita-center/react-dadata-box#55]
Хотелось бы иметь возможность вводить произвольное значение в поле. Текущая реализация вызывает событие onChange только при выборе пункта из списка.

**Comment by RUVATA** [comment]
Для реализации требуемой вам функциональности можно и предусматривается использовать [customInput](https://github.com/orbita-center/react-dadata-box#custominput-)
я подготовил для вас пример применения на codesandbox - см. [customInput use sample](https://codesandbox.io/s/custominput-58oi9)

**PS**: реализация такова, так как поле подразумевает значение - структуру (объект из списка предложенных DaData, в случае если предоставлять в базовый **onChange** - объект всегда - придется проводить дополнительные проверки значения, если имитировать объект DaData - то это "грязная сигнатура" (и ломает строгость типов TS), и т.д. 
для частных случаев разработана возможность частной реализации компонента ввода (customInput) все подобные кейсы могут быть обслужены разработчикам через его назначение)

**PPS**: возможно вы пытаетесь обработать случай когда от DaData не приходит вариантов ответа, для текущего **query** - для таких случаев предусмотрен специальный хендлер см. [onIdleOut](https://github.com/orbita-center/react-dadata-box#onidleout-) который срабатывает именно в таких случаях и как раз передает текущее значения поля ввода.

**Comment by RUVATA** [comment]
@ekabolotina, была ли вам полезна приведенная мной информация ? получилось ли решить вашу функциональную задачу при помощи **customInput** ?
