### ISSUE TITLE
Баг - не закрывается suggestions Popup при клике на TAB

### ISSUE THREAD

**Issue by vanhock** [orbita-center/react-dadata-box#59]
Если кликнуть на tab пока подсказки не показались, подсказки не скрываются на blur.
У себя в проекте решил так:
`const handleInputBlur = (e) => {
	setTimeout(() => {
	    inputEl.current.onInputBlur(e);
	}, 300);
};

<ReactDadataBox
	query={value}
	ref={inputEl}
        ...
`

На мой взгляд, это баг. 
Разработчики, исправьте это, плиз!

**Comment by RUVATA** [comment]
@vanhock
at now v1.3.5 released on NPM, welcome to update.
