### ISSUE TITLE
Using with Next.js

### ISSUE THREAD

**Issue by v-lavrinenko91** [orbita-center/react-dadata-box#63]
An error occurs when using a package with next.js: https://github.com/vercel/next.js/blob/master/errors/css-npm.md

Possible Ways to Fix It:
Reach out to the maintainer and ask for them to publish a compiled version of their dependency.
Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations.

**Comment by RUVATA** [comment]
@v-lavrinenko91 
Hm... the solution assumes built-in styles, target bundle is composed from index.js and index.css files, yes - index.js imported index.css.
IMHO - there are a lot of such solutions, what do Next.js with them

What is suggested for me to change or fix?
Make CSS inline into the JSX style tag inside index.js?

**Comment by v-lavrinenko91** [comment]
> @v-lavrinenko91
> Hm... the solution assumes built-in styles, target bundle is composed from index.js and index.css files, yes - index.js imported index.css.
> IMHO - there are a lot of such solutions, what do Next.js with them
> 
> What is suggested for me to change or fix?
> Make CSS inline into the JSX style tag inside index.js?

"> Make CSS inline into the JSX style tag inside index.js? - "Yes, I think this is a possible solution.

**Comment by RUVATA** [comment]
@v-lavrinenko91 
Make CSS inline, IMHO is not "Jedi Path" :)
It will be excess/overkill for other users of lib (not on Next.js stack)
And i'am afraid the backport troubles after update, with already declared in projects user's custom styling.

May be as good idea - make custom export of special case
(for users that it needed, eg Next.js stack)
where source not includes 'import.css' and user's minde to do it manually at main point of application or near placed with import of lib in the target source code?

A you have error on build your code, or this is static analyze warning ?
А you ready for test proposed solution in you case, if i make separate branch with this patch (previously setup lib from github-branch for check, whitout excess release on NPM) ?

**Comment by v-lavrinenko91** [comment]
> @v-lavrinenko91
> Make CSS inline, IMHO is not "Jedi Path" :)
> It will be excess/overkill for other users of lib (not on Next.js stack)
> And i'am afraid the backport troubles after update, with already declared in projects user's custom styling.
> 
> May be as good idea - make custom export of special case
> (for users that it needed, eg Next.js stack)
> where source not includes 'import.css' and user's minde to do it manually at main point of application or near placed with import of lib in the target source code?
> 
> A you have error on build your code, or this is static analyze warning ?
> А you ready for test proposed solution in you case, if i make separate branch with this patch (previously setup lib from github-branch for check, whitout excess release on NPM) ?

"May be as good idea - make custom export of special case" - it is a good idea too)
"A you have error on build your code, or this is static analyze warning ?" - error on build
"А you ready for test proposed solution in you case, if i make separate branch with this patch (previously setup lib from github-branch for check, whitout excess release on NPM) ?" - yes, i`am ready)

**Comment by RUVATA** [comment]
@v-lavrinenko91 
over the weekend I discussed our initiative with some of the library's contributors and users

**Decision**: for a multiple objective reason, separate export within the standard delivery - is not good solution.
As an alternative, I will develop a script that, when the library is released on NPM, will be duplicate the delivery with a separate _dist-tag_, as _"next-js"_ (or you may have any another proposition for tag name, that will be more semantic and universal for our case eg _"css-unbudled"_ ?)

users that’s need our case - may install lib as
`npm -install react-dadata-box@next-js`

on that dist-tag, always in future, will be placed latest version of library with unbundled CSS and excluded CSS import in main **index.js** file. Users of this version will have to connect CSS manually from **index.css** of library in their entrypoints.

It's normally solution for you ?

**Comment by v-lavrinenko91** [comment]
> @v-lavrinenko91
> over the weekend I discussed our initiative with some of the library's contributors and users
> 
> **Decision**: for a multiple objective reason, separate export within the standard delivery - is not good solution.
> As an alternative, I will develop a script that, when the library is released on NPM, will be duplicate the delivery with a separate _dist-tag_, as _"next-js"_ (or you may have any another proposition for tag name, that will be more semantic and universal for our case eg _"css-unbudled"_ ?)
> 
> users that’s need our case - may install lib as
> `npm -install react-dadata-box@next-js`
> 
> on that dist-tag, always in future, will be placed latest version of library with unbundled CSS and excluded CSS import in main **index.js** file. Users of this version will have to connect CSS manually from **index.css** of library in their entrypoints.
> 
> It's normally solution for you ?

Yes, great! For next.js, **index.css** can be connected globally аnd the problem will be solved.

**Comment by RUVATA** [comment]
@v-lavrinenko91 
At now i published current version (v1.3.6) with needed modifications (excluded import css declaration)
![image](https://user-images.githubusercontent.com/2040022/109983599-09132680-7d14-11eb-95f6-592246fa63e2.png)
please - can you try to install package from dist-tag 'next-js'
`npm -install react-dadata-box@next-js`
And try to build you'r Next.js application with this version of package
Please don't forget import styles manually in you entypoint from /dist/index.css 

I'll wait your feedback, if it is allright - i update documentation and use our developments to publish next patch (v1.3.7) by new CI (added postpublish script).

**Comment by v-lavrinenko91** [comment]
> @v-lavrinenko91
> At now i published current version (v1.3.6) with needed modifications (excluded import css declaration)
> ![image](https://user-images.githubusercontent.com/2040022/109983599-09132680-7d14-11eb-95f6-592246fa63e2.png)
> please - can you try to install package from dist-tag 'next-js'
> `npm install react-dadata-box@next-js`
> And try to build you'r Next.js application with this version of package
> Please don't forget import styles manually in you entypoint from /dist/index.css
> 
> I'll wait your feedback, if it is allright - i update documentation and use our developments to publish next patch (v1.3.7) by new CI (added postpublish script).

It seems that nothing changed
![error](https://user-images.githubusercontent.com/20818113/110004281-4f728080-7d28-11eb-87a8-c7c0aa639f42.png)

**Comment by RUVATA** [comment]
@v-lavrinenko91
Sorry - something went wrong.
Now I will correct the situation in the package, the assembly really went without adjustments.

i'am will notify in this thread - when i publish new version.

**Comment by RUVATA** [comment]
@v-lavrinenko91 
![image](https://user-images.githubusercontent.com/2040022/110127171-5952bd00-7dd6-11eb-9e81-bf4cf29ad65a.png)
please try to reinstall package, i published fixed version

**Comment by v-lavrinenko91** [comment]
> @v-lavrinenko91
> ![image](https://user-images.githubusercontent.com/2040022/110127171-5952bd00-7dd6-11eb-9e81-bf4cf29ad65a.png)
> please try to reinstall package, i published fixed version

It Works!) Thanks a lot from all next.js users)

**Comment by RUVATA** [comment]
@v-lavrinenko91 
At this moment I am preparing a new version for release [v1.3.7](https://github.com/orbita-center/react-dadata-box/pull/64) [ #64 ]
This version don't have any features/proposals or other logic, it is minor updates with infrastructure
(our case with script of parallel publish _'lates'_ and _'next-js'_ dist tag), TS typing's fix and documentation fix.
I am not sure that, after install package from dist-tag (_'next-js'_) and after next release, when user doing

`npm update`

package will updates within the confines of 'next-js' tag, **I am afraid that may occur switching to 'latest' tag**.

I would like to ask you to also participate in the behavior study after I publish the release.
(i'am will notify that by fact in this thread)

**Comment by v-lavrinenko91** [comment]
> @v-lavrinenko91
> At this moment I am preparing a new version for release [v1.3.7](https://github.com/orbita-center/react-dadata-box/pull/64) [ #64 ]
> This version don't have any features/proposals or other logic, it is minor updates with infrastructure
> (our case with script of parallel publish _'lates'_ and _'next-js'_ dist tag), TS typing's fix and documentation fix.
> I am not sure that, after install package from dist-tag (_'next-js'_) and after next release, when user doing
> 
> `npm update`
> 
> package will updates within the confines of 'next-js' tag, **I am afraid that may occur switching to 'latest' tag**.
> 
> I would like to ask you to also participate in the behavior study after I publish the release.
> (i'am will notify that by fact in this thread)

Sure, no problem, you can contact me. Telegram, whatsApp +79037868820

**Comment by RUVATA** [comment]
@v-lavrinenko91  
at now published [1.3.7 version](https://www.npmjs.com/package/react-dadata-box/v/1.3.7) of react-data-box lib

----
1.3.7 contain only minor and cosmetic updates, and some fixes, can you check that tagged 'next-js' version was updated successfully ?
'next-js' version also was published on NPM
see: https://www.npmjs.com/package/react-dadata-box/v/1.3.7-next-js

Can you give me feedback about it ?
