### ISSUE TITLE
Compatibility with React 17 and 18

### ISSUE THREAD

**Issue by vommuan** [orbita-center/react-dadata-box#68]
Is there any plans to do this package compatible with React 17 and 18?

package.json contains "^16.4.2" React version as a dependency, And it worked 3 months ago with React 17. But Node moved their LTS Docker Alpine version to 16 and after that versions became incompatible.

Log from installation is below:

```
Status: Downloaded newer image for node:lts-alpine
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.16.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.16.0>
npm notice Run `npm install -g npm@8.16.0` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: app@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.4.2" from react-dadata-box@1.3.6
npm ERR! node_modules/react-dadata-box
npm ERR!   react-dadata-box@"^1.3.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Thank you!

**Comment by RUVATA** [comment]
Hi, thanks for your attention.

I stopped active support & contribution since leave [orbita-center](https://github.com/orbita-center) company. My ex-colleagues apparently continue active using of this package, but never support or contribution it. (despite has all rights and competensions)

If you have insight what needed be done to resolve this issue  - welcome to open PR with it. I can approve, form it as hotfix, merge and publish minor version of lib.
But give grants of resolve it (by me) - i cannot, for me it is forgotten pet-project, sorry, at now i work in Yandex - and not have a lot of free time.

**Comment by vommuan** [comment]
Thank you for information.

**Comment by RUVATA** [comment]
@vommuan 
I returned to this issue, check's that the lib is fine works on 17.0.2 (node:its-alpine threshold) & 18.2.0 (latest alpha)

see: https://codesandbox.io/s/react-dadata-box-example-forked-5fs9gq (fork of base example - with updated versions of react & react-dom)

That is, the library version is compatible with React 17 & 18
declared in package.json versions - denote only the lower according to the version of the dependencies.

I will up declared react dependencies to
```
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
```
at nearest release #64 of lib thats coming soon

**Comment by RUVATA** [comment]
@vommuan 
at now published [1.3.7 version](https://www.npmjs.com/package/react-dadata-box/v/1.3.7) of react-data-box lib

I invite you to update the version of the package - and post feedback about it solves your problem or give your requested functionality

**Comment by vommuan** [comment]
Thank you for your attention to this issue. But there is another problem through installation.

Log is below:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-highlight-words@0.12.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.2" from the root project
npm WARN   27 more (@devexpress/dx-react-chart, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-highlight-words@0.12.0
npm WARN node_modules/react-highlight-words
npm WARN   react-highlight-words@"^0.12.0" from react-dadata-box@1.3.7
npm WARN   node_modules/react-dadata-box
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-highlight-words@0.12.0
npm WARN   node_modules/react-highlight-words
npm WARN     react-highlight-words@"^0.12.0" from react-dadata-box@1.3.7
npm WARN     node_modules/react-dadata-box
```

You should increase your dependency package react-highlight-words to version 0.18, which is compatible with React 17 and 18. Or you can replace `^0.12.0` by `>=0.12`. You can check this page for version control of npm package: https://semver.npmjs.com/

**Comment by RUVATA** [comment]
@vommuan 
i fixed declared 'react-highlight-words' dependency to latest version 0.18.0
at new minor release of lib #74 (1.3.8)

can you check that you haven't NPM WARN's that referents to react-data-boxlib presently ?

**Comment by vommuan** [comment]
Checked. Problem is solved. Thank you very much.
