### ISSUE TITLE
Вопрос по fms_unit.

### ISSUE THREAD

**Issue by HeisPovedim** [orbita-center/react-dadata-box#69]
Можно ли как-то получить код подразделение и записать его в отдельное окно только цифрами? А остальную часть, то есть кем выдан, в другое окно?

**Comment by HeisPovedim** [comment]
Я понял как это сделать, но теперь у меня появилась новая проблема, при использовании `customInput` и меня перестает работать навигация, и при нажатии на TAB не скрываются подсказки. Что я могу сделать в этом случаи?
Вот код:
```
  <ReactDadataBox
  token="0a6d8a91d324ad8afcbb98473979e7329d944fd6"
  type='fms_unit'
  onChange={suggestion => handlerDataSuggestion(suggestion)}
  customInput = {( {onChange} ) => (
    <NumberFormat
         format="###-###"
         allowEmptyFormatting
         mask="_"
         // className={className}
         onValueChange={(values) => {
             const { formattedValue, value } = values;
             // formattedValue = $2,223
             // value ie, 2223
             setDataSuggestion(value)
             console.log(value)
         }
         onChange={ (event) => {
           onChange(event)
           setOUCode(event.target.value)
         }}
         value={ouCode}
     />
   )}
/>
```

**Comment by RUVATA** [comment]
@HeisPovedim 
Добрый день, давайте попробуем начать с прототипа.
сделайте форк от песочницы https://codesandbox.io/s/react-dadata-box-example-g9xb0

убираем всё лишнее - оставляем основу вашего кейса, с учётом того решения, что у вас уже есть, попробуйте так-же формально (что-то вроде ТЗ), тезисно описать поведение которое вы хотели бы наблюдать, н/п:
- есть форма ввода (с которой работает пользователь)
- есть 2 лейбла - которые должны рефлексировать на выбранные данные заполняясь синхронно со значением поля ввода, отражая отдельные детальные поля из структуры DaDatа
и т.д. - и тогда попробуем с Вами что-то придумать, пока я слишком "туманно" понимаю задачу и проблемы с которыми вы столкнулись...

**PS**: я сам уже давно не работаю с этой библиотекой (оставил её поддержку и развитие коллегам, сменив место работы) но судя по всему они используют её As Is - не продолжая развития и поддержки :)

**Comment by HeisPovedim** [comment]
@RUVATA  Добрый день, залил все в CodesanBox как вы и сказали: https://codesandbox.io/s/nostalgic-allen-fuysuu . Проясню ситуацию ещё раз - у меня поле, куда вставляется код подразделения, проблема заключается в том, что если использовать react-dadata-box так ,как использую его я, то не работает навигация через стрелочки, то есть если попробовать в выпадающем списке что-нибудь выбрать с помощью клавиатуры, то курсор начинает перемещаться по полю, а не по окну подсказак.

**Comment by RUVATA** [comment]
@HeisPovedim 
Для решения вашей задачи достаточно пробросить до вашего кастомного компонента хендлер определяющий обработку действий по вводу символов/chars (как правило "ввод с клавиатуры") **`onKeyDown`** 
см. его определие в интерфейсе входных **props** для **`customInput`** **[BaseInputProps](https://github.com/orbita-center/react-dadata-box#custominput-)**
что так-же отражено в декларации типов TypeScript для библиотеки см [index.d.ts:367](https://github.com/orbita-center/react-dadata-box/blob/39a98fa6950c48c7d84fbae5d15cfbb30711bb6c/index.d.ts#L367)

<img src="https://user-images.githubusercontent.com/2040022/187066382-8b5eafec-6440-4871-9d34-14db0ba94c10.png" width="450">

см. [форк вашего sandbox с внесенной правкой](https://codesandbox.io/s/hungry-fast-7r3ldc?file=/src/App.js)

⚠️ прошу обратить внимание что интерфейсом **BaseInputProps** определяются так-же хендлеры **onBlur**, **onFocus** которые (в штатном кейсе) так-же подразумевается проксировать в дочерний компонент (или вызывать их опосредованно в декларируемых обработчиках того-же типа событий), т.к. эти обработчики так-же обеспечивают, в той или иной мере, стабильное предсказуемое поведение и консистентность состояния и флагов компонента react-dadata-box.

👉 т.е. идеология этого механизма (**`customInput`**) - подразумевает, что для дочернего компонента предоставляется набор пропсов которые в идеале должны быть установлены для дочернего компонента (тот в свою очередь должен поддерживать интерфейс базового **input**-а ("быть инпутом")), и если  **autocomplete**, **className** и **placeholder** (можно опустить) т.к. они "механически инертные" - то **обработчики** ⚠️ обязательно надо или проксировать или вызывать опосредованно в декларируемых обработчиках того-же типа обрабатываемого события.

**PPS**: Если мне удалось вам помочь, и ваша проблема решена - приглашаю закрыть данный issue

**Comment by HeisPovedim** [comment]
Спасибо большое, правда все работает, ещё вопрос, можно ли изменить значения в выпадающем списке? То есть если сейчас попробовать ввести что-нибудь в поле, при выпадающим подсказках, помимо текста писался ещё и код подразделения? Как на картинке.
![изображение](https://user-images.githubusercontent.com/77213018/187077857-a4dfb2d5-2090-4c91-be75-e2440acc1905.png)

**Comment by RUVATA** [comment]
В текущем решении - какой либо кастомизации контента для саджестов не предусмотрено (кроме стилизации), есть несколько фиксированных варианта для разных типов фетчинга, общий вариант с подсветкой найденного фрагмента + `type === 'party' || type === 'bank'` (есть доп. информация см. компонент **SuggestionInfo**)
Отличная опция для развития - если подготовите PR с такой доработкой - с удовольствием приму участие в утверждении, code review и принятии решения в очередную версию библиотеки.

**PS**: сегодня как раз добрались руки - добить висящий уже больше года 1.3.7 (минорный)... очень надеюсь
