### ISSUE TITLE
adding a setting that will allow you to specify the server address and API

### ISSUE THREAD

**Issue by romanown** [orbita-center/react-dadata-box#76]
I suggest adding a setting that will allow you to specify the server address and API to expand the use cases with a non-standard connection.

**Comment by romanown** [comment]
предлагаю добавить настройку которая позволит указывать адрес сервера и апи для расширения вариантов использования при нестандартном подключении.

**Comment by romanown** [comment]
функционал присутствует, хотя не найден в типах.

**Comment by RUVATA** [comment]
@romanown

the functionality that interests you is implemented through **prop** `customEndpoint`

→ declared in types
https://github.com/orbita-center/react-dadata-box/blob/master/index.d.ts#L455

→ declared and described in JSDoc format
https://github.com/orbita-center/react-dadata-box/blob/master/index.d.ts#L424

→ described in the documentation
https://github.com/orbita-center/react-dadata-box#customendpoint- [EN]
https://github.com/orbita-center/react-dadata-box/blob/master/README.ru.md#customendpoint- [RU]

----

Is this what you needed ? Or I misunderstand your request ?

**Comment by romanown** [comment]
спасибо, я это потом нашел и поэтому закрыл обращение. или забыл закрыть. все хорошо, все работает.
