### ISSUE TITLE
upgrade dependencies for react 18

### ISSUE THREAD

**Issue by romanown** [orbita-center/react-dadata-box#78]
i have error react-dadata-box@1.3.4" has unmet peer dependency "prop-types@^15.6.2".
warning " > react-dadata-box@1.3.4" has incorrect peer dependency "react@^16.4.2".
warning " > react-dadata-box@1.3.4" has incorrect peer dependency "react-dom@^16.4.2".

**Comment by vommuan** [comment]
The same issue: https://github.com/orbita-center/react-dadata-box/issues/68

Upgrade your react-dadata-box version to latest.

**Comment by romanown** [comment]
thanks. i upgrade it.
